resolver: nightly-2020-09-10 # ghc 8.10.2
extra-deps:
  # - typed-process-0.2.5.0
  - conduit-extra-1.3.2 # switching from 1.3.2 to 1.3.3 fixes the crash on lts-13.26

# The issue reproduces faster (after less loop iterations,
# from "within a minute" to "within a second") when I use my own
# built GHC from the `ghc-8.10` branch (exact commit is 35c7451),
# with these `make` settings:
#     BuildFlavour = perf
#     GhcLibHcOpts += -g3
#     GhcRtsHcOpts += -g3
# which I can enable with the following:

# extra-path:
# - /home/niklas/opt/ghc-8.10.2-lz4-memory-error-dwarf/bin
# system-ghc: true
# skip-ghc-check: true
