# resolver: lts-13.25 # fails
resolver: lts-13.26 # fails
# resolver: lts-13.27 # works
# resolver: lts-13.28 # works
# resolver: lts-13.30 # works
# resolver: lts-14.27 # works
# resolver: lts-14.23 # works
# resolver: lts-14.0 # works
# extra-deps: []
extra-deps:
  # - typed-process-0.2.5.0
  - conduit-extra-1.3.2 # switching from 1.3.2 to 1.3.3 fixes the crash on lts-13.26
